import '/scss/main.scss';
import { useTheme } from './componets/theme';
import { useHeaderTabs } from './componets/headerTabs';
import { useBurger } from './componets/burger';
import { useModal } from './componets/modal';
import FsLightbox from 'fslightbox';
import { useServicesTabs } from './componets/servicesTabs';
useTheme();
useHeaderTabs();
useBurger();
useModal();
useServicesTabs();